# ============================================================
# TIMING
# ============================================================

[timing]
target_fps = 144
fixed_delta_time = 0.016666666666666666


# ============================================================
# DEBUG
# ============================================================

[debug]
overlay = false


# ============================================================
# AUDIO DEVICE
# ============================================================

[audio]
frequency = 48000
channels = 2


# ============================================================
# AUDIO BUFFERING
# ============================================================

[audio_buffer]
target_queue_frames = 2048
max_update_frames = 2048